### ISSUE TITLE
Upgrade to php 7.1+?

### ISSUE THREAD

**Issue by kunicmarko20** [exercism/php#216]
What do you think about upgrading all exercises to php 7.1+? Adding types and return types

**Comment by petemcfarlane** [comment]
I think it's probably a good idea where it makes sense, but can you think of any breaking changes? And do you think we should use the [current version PHP 7.2](http://php.net/supported-versions.php) rather than 7.1 who's active support ends in 1 months time?

<img width="919" alt="screenshot 2018-10-02 at 09 59 26" src="https://user-images.githubusercontent.com/3472717/46336141-367eb600-c62a-11e8-8d2d-7bef1a620d45.png">

Can you think of any exercises which would benefit from adding return types to the test/implementation, as an example for discussion? Or rather can you think of any exercises that are held back because of the version, or that wouldn't work if someone wrote a solution in PHP 7.2?

**Comment by kunicmarko20** [comment]
I can't think of any BC? the only problem I can think of is that not everyone has 7.2 on their machine, that is why I said 7.1. Someone suggested providing a docker container on slack but that is the same thing, not everyone has docker.

The only thing 7.2 brings is `object`, I think we will also need that.

I think that the benefit would be that people learning PHP should use the new feature of language with types and should be aware of that.

**Comment by petemcfarlane** [comment]
Yeah PHP 7.1 will probably be more widely available than requiring 7.2 by default on most OSs. Would you like to update an example exercise to see how different it might be and to gauge how much effort it will take vs the benefits? That would be great!

**Comment by kunicmarko20** [comment]
I will do an example but I don't mind updating everything, so let's say there is not that much effort.

**Comment by jeslopcru** [comment]
I think, It would be easier install using docker. what do you think?

**Comment by petemcfarlane** [comment]
I've been put off Docker from personal experience, but it's a pretty popular tool. Perhaps we could offer it as an option, for those who already use docker? @jeslopcru would you like to write the installation /setup instructions in the docs directory and submitting a PR? Thanks!
