### ISSUE TITLE
Instructions are Linux-centric

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/php#346]
https://twitter.com/remotely_ruth/status/1368254180440166400

`wget` is not available on Mac nor Windows. Given that this is in the Hello World instructions, my assumption is that the entire documentation is full with linux only commands.

Ping me (here or slack) if you want my steps how I would install PHP on Windows.

**Comment by neenjaw** [comment]
It probably is, I'll talk to you on slack

**Comment by arueckauer** [comment]
As a side note:

The [installation](https://github.com/exercism/php/blob/main/docs/INSTALLATION.md#install-php) documentation provides a section for both MacOS and Windows. While the instructions for an installation on Windows should still be fine, MacOS would need an update, since [Liip](https://php-osx.liip.ch/) no longer updates their binaries.
