### ISSUE TITLE
Error when running php/resistor-color test

### ISSUE THREAD

**Issue by DavidLJz** [exercism/php#414]
```
There was 1 error:

1) ResistorColorTest::testColors
Use of undefined constant COLORS - assumed 'COLORS' (this will throw an Error in a future version of PHP)

/home/user/exercism/php/resistor-color/ResistorColorTest.php:51
```
The error is present in the online editor too

**Comment by neenjaw** [comment]
Can you paste your solution?

**Comment by DavidLJz** [comment]
Sure

```php
<?php

declare(strict_types=1);

function colorCode(string $color): int
{
    $colors = [
        'black' => 0,
        'brown' => 1,
        'red' => 2,
        'orange' => 3,
        'yellow' => 4,
        'green' => 5,
        'blue' => 6,
        'violet' => 7,
        'grey' => 8,
        'white' => 9,
    ];

    return $colors[ strtolower($color) ];
}

```
All files have their original names.

**Comment by neenjaw** [comment]
Ok cool, nice solution.  The error is originating because the test file expects you to define `COLORS` as a constant in the global scope (see the last test here: `https://github.com/exercism/php/blob/main/exercises/practice/resistor-color/ResistorColorTest.php`).  Since you are defining it within your function, the test case can't access it.

**Comment by DavidLJz** [comment]
Oh I see. I think the instructions could be a bit more explicit then.

**Comment by neenjaw** [comment]
Yes, at the very least it could be prudent to move it up to the first test case, since it would probably change the construction of a solution.
