### ISSUE TITLE
[Resistor Color] Instructions needed

### ISSUE THREAD

**Issue by MariusT-Devspace** [exercism/php#482]
Hey guys, running the exercise I get the following error: Undefined constant "COLORS". Reading from another issue that's been closed, COLORS is a constant that should be declared by the user globally. However there's no instructions to do this, and this could make it harder for beginner programmers to solve the exercise. I'm not good at writing, so If someone could add some instructions it would be great. 
Cheers!

**Comment by kotp** [comment]
When you are running the tests, is there a test that complains about this not existing?

This may not be an exercise that is meant to "teach programming", but instead to practice the language.  Slightly different way to present information, because it assumes programming experience, just not in this language.

With that in mind, how does it change the problem presented?  Also, can you reference the "another issue that's been closed" so that we can see it too, to get context of the conversation?

**Comment by jwhitt3r** [comment]
I do think this challenge could be updated to provide some more guidance, I would be happy to adapt it.

**Comment by neenjaw** [comment]
@jwhitt3r if you open an improvement I'll review it

**Comment by neenjaw** [comment]
@MichaelBunker merged a change to alter this requirement to be a method that returns an array of colors to improve the exercise and address this issue.
